# Generated by Django 3.2 on 2022-05-07 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('login', models.CharField(max_length=40, verbose_name='Логин пользователя')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name='Фамилия пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=17, verbose_name='Номер телефона')),
                ('orders', models.ManyToManyField(blank=True, related_name='related_user', to='orders.Order', verbose_name='Заказы пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
