# Generated by Django 3.2 on 2022-05-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='Номер телефона')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name='Фамилия покупателя')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new_order', 'Новый заказ'), ('order_in_process', 'Заказ в обработке'), ('order_ready', 'Заказ готов'), ('order_done', 'Заказ выполнен')], default='new_order', max_length=20, verbose_name='Статус заказа')),
                ('orderType', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=20, verbose_name='Тип заказа')),
                ('payment', models.CharField(choices=[('online', 'Онлайн оплата'), ('cash', 'Оплата наличными')], default='online', max_length=20, verbose_name='Тип оплаты')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к заказу')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('overall_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='orders.OrderItem', verbose_name='Продукты'),
        ),
    ]
